/*
 * File: app/store/SearchResults.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NewsHolder.store.SearchResults', {
    extend: 'Ext.data.Store',

    requires: [
        'NewsHolder.model.SearchResult'
    ],

    config: {
        autoLoad: true,
        model: 'NewsHolder.model.SearchResult',
        storeId: 'searchResultsStore',
        proxy: {
            type: 'jsonp',
            url: 'http://iamapark.cafe24.com/fullrss/makefulltextfeed.php?url=openapi.naver.com%2Fsearch%3Fkey%3D907ed5cd8ab441dc61ffb0016280e906%26query%3D%25EC%25A3%25BC%25EC%258B%259D%26target%3Dnews&format=json',
            reader: {
                type: 'json',
                rootProperty: 'rss.channel.item'
            }
        }
    }
});