/*
 * File: app/view/RssPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NewsHolder.view.RssPanel', {
    extend: 'Ext.Panel',
    xtype : 'rsspanel',
    id : 'rssPanel',
    
    config: {
        layout: {
            type: 'fit'
        },
        items: [
			{
			    xtype: 'fieldset',
			    docked: 'top',
			    id: 'rssFieldSet',
			    layout: {
			        align: 'stretchmax',
			        type: 'vbox'
			    },
			    items: [
			        {
			            xtype: 'textfield',
			            id: 'rssNameText',
			            label: 'RSS 명'
			        },
			        {
			        	xtype: 'textfield',
			        	id: 'rssUrlText',
			        	label: 'RSS 주소'
			        },
			        {
			        	xtype: 'textfield',
			        	id: 'rssImageText',
			        	label: 'RSS 이미지 주소'
			        },
			        {
			            xtype: 'button',
			            id: 'rssAddButton',
			            ui: 'confirm',
			            iconCls: 'add',
			            iconMask: true
			        }
			    ]
			},                
            {
                xtype: 'dataview',
                id: 'RssList',
                itemId: 'mydataview',
                itemTpl: [
                    '<div style="width: 100px; height: 100px; float:left">',
                    '<img src="{rssImage}"><br>',
                    '{rssName}',
                    '</div>'
                ],
                store: 'rssStore'
            },
            
        ]
    }

});