/*
 * File: app/view/RssPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NewsHolder.view.RssPanel', {
    extend: 'Ext.Panel',
    xtype : 'rsspanel',
    
    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'RSS 추가',
                items: [
                    {
                        xtype: 'button',
                        id: 'Home',
                        ui: 'back',
                        iconCls: 'home',
                        iconMask: true
                    }
                ]
            },
            {
                xtype: 'dataview',
                height: '',
                id: 'RssList',
                itemId: 'mydataview',
                ui: '',
                itemTpl: [
                    '<div style="width: 100px; height: 100px; float:left">',
                    '<img src="{rssImage}"><br>',
                    '{rssName}',
                    '</div>'
                ],
                store: 'rssStore'
            },
            {
                xtype: 'fieldset',
                docked: 'top',
                id: 'rssFieldSet',
                margin: '',
                ui: '',
                layout: {
                    align: 'stretchmax',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'textfield',
                        id: 'rssAddressText',
                        width: '85%',
                        label: 'RSS'
                    },
                    {
                        xtype: 'button',
                        id: 'rssAddButton',
                        ui: 'action',
                        width: '15%',
                        iconCls: 'add',
                        iconMask: true
                    }
                ]
            }
        ]
    }

});