/*
 * File: app/controller/RssController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NewsHolder.controller.RssController', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'RssModel'
        ],
        views: [
            'RssPanel'
        ],

        refs: {
            addButton: '#rssAddButton',
            rssItem: '#rssList',
            	
        },

        control: {
            'addButton': {
                tap: 'onRssAddButtonTap'
            },
            'rssItem': {
                itemtap: 'onRssListItemTap'
            }
        }
    },


    onRssAddButtonTap: function(button, e, options) {
        //console.log("Rss Add Button tap!");
        
        var store = Ext.data.StoreManager.lookup('mainStore');
        var rssname = Ext.getCmp('rssNameText').getValue();
        var rssurl = Ext.getCmp('rssUrlText').getValue();
        var rssimg = Ext.getCmp('rssImageText').getValue();
        
        store.add({ mainRssName : rssname,
        	mainRssUrl : rssurl ,
        	mainRssImage : rssimg });
        store.sync();
    },

    onRssListItemTap: function(dataview, index, target, record, e, options) {
        //console.log("rssList Item tap");    	
    	
        var store = Ext.data.StoreManager.lookup('mainStore');
        var rssname = record.get('rssName');
        var rssurl = record.get('rssUrl');
        var rssimg = record.get('rssImage');
        
        store.add({ mainRssName : rssname,
        	mainRssUrl : rssurl ,
        	mainRssImage : rssimg });
        store.sync();    	
    	
    }

});